Test IGNORE_ERROR

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -29,6 +29,7 @@ jobs:
 
     env:
       DRY_RUN: ${{ inputs.dry-run && 'echo' || '' }}
+      IGNORE_ERROR: ${{ inputs.dry-run && '|| true' || '' }}
 
     steps:
       - name: Print inputs
@@ -45,7 +46,11 @@ jobs:
           set -x
           echo "LIST_GIT: $LIST_GIT"
           echo "Listing files regardless of dry-run:"
-          ls -l ${LIST_GIT:-} .github
+          ls -l ${LIST_GIT:-} .github ${IGNORE_ERROR:-}
+
+          if [ -n "$IGNORE_ERROR" ]; then
+            echo "Dry run: Skipping errors from promotion check"
+          fi
 
           echo "Listing files only if not dry-run:"
           $DRY_RUN ls -l ${LIST_GIT:-} .github
